#!/usr/bin/env python3
"""Generate ready-to-run shard notebooks from SBTS_CANONICAL_A100.ipynb.

A FULL run is tens of hours, so it is normally split across parallel Colab
sessions pointed at the same run id. Editing the knobs by hand before every
session is easy to get wrong, so the variants are generated instead: each one
opens with RUN_MODE and SHARD_GENERATORS already set, and is otherwise byte
for byte the canonical notebook.

These files are GENERATED. Edit SBTS_CANONICAL_A100.ipynb and re-run:

    python3 tools/make_shard_notebooks.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "notebooks" / "SBTS_CANONICAL_A100.ipynb"
OUT_DIR = ROOT / "notebooks" / "shards"

# name -> (SHARD_GENERATORS literal, what the session does)
VARIANTS = {
    "run_GBM": ("(\"GBM\",)",
                "trains the 60 GBM configurations, then stops"),
    "run_Heston": ("(\"Heston\",)",
                   "trains the 60 Heston configurations, then stops"),
    "run_SBTS": ("(\"SBTS\",)",
                 "trains the 60 SBTS configurations, then stops"),
    "run_Heston_SBTS": ("(\"Heston\", \"SBTS\")",
                        "trains the 120 Heston and SBTS configurations, then stops"),
    "run_analysis": ("None",
                     "trains anything still missing, then runs the audit, "
                     "evaluation, statistics, diagnostics, tables and manifest "
                     "over every generator"),
}

BANNER = """> ## Generated file — open and run, no setup needed
>
> `RUN_MODE = "FULL"` and `SHARD_GENERATORS = {shard}` are already set.
> This session **{does}**.
>
> `RESUME_RUN_ID` is left as `None`, which resumes the newest run with the same
> `config_hash`; completed configurations are skipped, a finished Phase 1 is
> reused, and an interrupted phase continues from the epoch it reached. Point
> every parallel session at the same run so they share one run directory.
>
> Sharded sessions stop after Cell 19 with `ShardTrainingComplete` — that is
> the expected end, not an error. Run `run_analysis.ipynb` once every shard has
> finished.
>
> Do not edit this file: it is generated from `notebooks/SBTS_CANONICAL_A100.ipynb`
> by `tools/make_shard_notebooks.py`. Edit the canonical notebook and
> regenerate.

"""


def build(master: dict, name: str, shard: str, does: str) -> dict:
    nb = json.loads(json.dumps(master))          # deep copy
    patched_knobs = 0
    for cell in nb["cells"]:
        src = "".join(cell["source"])
        if cell["cell_type"] == "markdown" and "# SBTS Canonical Experiment" in src:
            cell["source"] = [l + "\n" for l in
                              BANNER.format(shard=shard, does=does).split("\n")] + cell["source"]
        elif cell["cell_type"] == "code" and re.search(r"^RUN_MODE = ", src, re.M):
            src, n1 = re.subn(r'^RUN_MODE = "SMOKE".*$',
                              'RUN_MODE = "FULL"', src, count=1, flags=re.M)
            src, n2 = re.subn(r"^SHARD_GENERATORS = None.*$",
                              f"SHARD_GENERATORS = {shard}", src, count=1, flags=re.M)
            patched_knobs = n1 + n2
            cell["source"] = [l + "\n" for l in src.split("\n")[:-1]] + [src.split("\n")[-1]]
            cell["outputs"] = []
            cell["execution_count"] = None
    if patched_knobs != 2:
        raise SystemExit(f"{name}: expected to patch 2 knobs, patched {patched_knobs}. "
                         f"Has Cell 0 changed?")
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
    return nb


def main() -> int:
    if not MASTER.exists():
        raise SystemExit(f"missing {MASTER}")
    master = json.loads(MASTER.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, (shard, does) in VARIANTS.items():
        nb = build(master, name, shard, does)
        dst = OUT_DIR / f"{name}.ipynb"
        dst.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
        print(f"wrote {dst.relative_to(ROOT)}  (SHARD_GENERATORS = {shard})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
