#!/usr/bin/env python3
"""Generate ready-to-run shard notebooks from SBTS_CANONICAL_A100.ipynb.

A FULL run is tens of hours, so it is split across parallel Colab sessions
that share one run directory. Editing knobs by hand before every session is
easy to get wrong, so the variants are generated: each opens with its knobs
already set and is otherwise byte for byte the canonical notebook.

The shipped pair is two T4 sessions that split every generator by SEED.
Halving the seeds cuts every generator/option/strike cell in two, so both get
the same amount of remaining work however far an earlier run already got.

These files are GENERATED. Edit SBTS_CANONICAL_A100.ipynb and re-run:

    python3 tools/make_shard_notebooks.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "notebooks" / "SBTS_CANONICAL_A100.ipynb"
OUT_DIR = ROOT / "notebooks" / "shards"

# name -> (knob overrides, what the session trains, which GPU it is meant for)
# The whole experiment is trained on T4 only: JOIN_ONLY_RUNS_ON_GPU makes every
# shard skip a run that any other GPU (e.g. the earlier A100 session) wrote to.
# Machine 1 had already worked through most of the even seeds when the odd
# seeds had to start over, so the odd seeds are split 3 + 2: machine 2 takes
# seeds 1, 3, 5 now and machine 1 takes seeds 7, 9 once its even seeds are
# done. Together they cover all 180 configurations with no overlap.
_T4 = {"JOIN_ONLY_RUNS_ON_GPU": '"T4"'}
VARIANTS = {
    "run_T4_1": ({"SHARD_SEEDS": "(0, 2, 4, 6, 8)", **_T4},
                 "seeds 0, 2, 4, 6, 8 of GBM, Heston and SBTS", "T4 — machine 1"),
    "run_T4_1b": ({"SHARD_SEEDS": "(7, 9)", **_T4},
                  "seeds 7, 9 of GBM, Heston and SBTS", "T4 — machine 1, "
                  "after run_T4_1 has stopped"),
    "run_T4_2": ({"SHARD_SEEDS": "(1, 3, 5)", **_T4},
                 "seeds 1, 3, 5 of GBM, Heston and SBTS", "T4 — machine 2"),
}

BANNER = """> ## Generated file — open it and run, nothing to set up
>
> Meant for: **{gpu}**. `RUN_MODE = "FULL"` and {knobs} are already set.
> This notebook trains **{does}**.
>
> It is one of three that share one run, all trained on T4:
>
> | Notebook | Where | Trains |
> |---|---|---|
> | `run_T4_1.ipynb` | machine 1 | seeds 0, 2, 4, 6, 8 |
> | `run_T4_1b.ipynb` | machine 1, after `run_T4_1` stops | seeds 7, 9 |
> | `run_T4_2.ipynb` | machine 2, in parallel | seeds 1, 3, 5 |
>
> Together they cover all 180 configurations with no overlap. Configurations
> that are already complete are skipped.
>
> **Only a run trained entirely on T4 is joined.** A run that another GPU (the
> earlier A100 session) wrote to is skipped, and the notebook prints why. Both
> machines must see the SAME Google Drive folder and print the SAME `run_id`
> in Cell 3. If a notebook finds no T4 run it stops in Cell 3 before training
> anything — that means this machine cannot see the other machine's Drive.
>
> **Whichever notebook finishes LAST carries straight on into the audit,
> evaluation, statistics (MCS), diagnostics and tables.** The others stop after
> Cell 19 with `ShardTrainingComplete`; that is the expected end, not an
> error. If all stop without the analysis — possible because Google Drive
> syncs between machines with a delay — run any one of them again: it finds
> all 180 complete and goes straight to the analysis.
>
> After a Colab disconnect, just run the same notebook again: completed
> configurations are skipped, a finished Phase 1 is reused, and an interrupted
> phase continues from the epoch it reached.
>
> Do not edit this file: it is generated from `notebooks/SBTS_CANONICAL_A100.ipynb`
> by `tools/make_shard_notebooks.py`. Edit the canonical notebook and
> regenerate.

"""


def build(master: dict, name: str, knobs: dict, does: str, gpu: str) -> dict:
    nb = json.loads(json.dumps(master))          # deep copy
    overrides = {"RUN_MODE": '"FULL"', **knobs}
    patched = 0
    for cell in nb["cells"]:
        src = "".join(cell["source"])
        if cell["cell_type"] == "markdown" and "# SBTS Canonical Experiment" in src:
            text = BANNER.format(
                knobs=" and ".join(f"`{k} = {v}`" for k, v in knobs.items()),
                does=does, gpu=gpu)
            cell["source"] = [l + "\n" for l in text.split("\n")] + cell["source"]
        elif cell["cell_type"] == "code" and re.search(r"^RUN_MODE = ", src, re.M):
            for knob, value in overrides.items():
                src, n = re.subn(rf"^{knob} = .*$", f"{knob} = {value}",
                                 src, count=1, flags=re.M)
                patched += n
            lines = src.split("\n")
            cell["source"] = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    if patched != len(overrides):
        raise SystemExit(f"{name}: expected to patch {len(overrides)} knobs, "
                         f"patched {patched}. Has Cell 0 changed?")
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
    return nb


def main() -> int:
    if not MASTER.exists():
        raise SystemExit(f"missing {MASTER}")
    master = json.loads(MASTER.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.ipynb"):
        if stale.stem not in VARIANTS:
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)} (no longer generated)")
    for name, (knobs, does, gpu) in VARIANTS.items():
        nb = build(master, name, knobs, does, gpu)
        dst = OUT_DIR / f"{name}.ipynb"
        dst.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
        print(f"wrote {dst.relative_to(ROOT)}  ({', '.join(f'{k} = {v}' for k, v in knobs.items())})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
