#!/usr/bin/env python3
"""Generate ready-to-run shard notebooks from SBTS_CANONICAL_A100.ipynb.

A FULL run is tens of hours, so it is normally split across parallel Colab
sessions pointed at the same run id. Editing the knobs by hand before every
session is easy to get wrong, so the variants are generated instead: each one
opens with RUN_MODE and SHARD_GENERATORS already set, and is otherwise byte
for byte the canonical notebook.

These files are GENERATED. Edit SBTS_CANONICAL_A100.ipynb and re-run:

    python3 tools/make_shard_notebooks.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "notebooks" / "SBTS_CANONICAL_A100.ipynb"
OUT_DIR = ROOT / "notebooks" / "shards"

# name -> (SHARD_GENERATORS literal, what the session does)
VARIANTS = {
    # The same split as the original article_gbm / article_heston_sbts pair.
    "run_GBM": ("(\"GBM\",)",
                "trains the 60 GBM configurations"),
    "run_Heston_SBTS": ("(\"Heston\", \"SBTS\")",
                        "trains the 120 Heston and SBTS configurations"),
}

BANNER = """> ## Generated file — open it and run, nothing to set up
>
> `RUN_MODE = "FULL"` and `SHARD_GENERATORS = {shard}` are already set.
> This notebook **{does}**. Its partner is the other file in `notebooks/shards/`
> (`run_GBM.ipynb` / `run_Heston_SBTS.ipynb`) — together they cover all 180.
>
> **Whichever of the two finishes LAST carries straight on into the audit,
> evaluation, statistics, diagnostics and tables. There is no third notebook.**
> The one that finishes first stops after Cell 19 with `ShardTrainingComplete`;
> that is the expected end, not an error. If the last one is interrupted before
> the analysis, simply run either notebook again: it finds all 180 complete,
> skips the training and goes straight to the analysis.
>
> `RESUME_RUN_ID` is left as `None`, so both notebooks join the existing run
> with the same `config_hash` — the one with the most completed
> configurations. Completed configurations are skipped, a finished Phase 1 is
> reused, and an interrupted phase continues from the epoch it reached.
>
> **Stop any session still running an older copy of the notebook before you
> start these**, or two processes will train the same configurations.
>
> Do not edit this file: it is generated from `notebooks/SBTS_CANONICAL_A100.ipynb`
> by `tools/make_shard_notebooks.py`. Edit the canonical notebook and
> regenerate.

"""


def build(master: dict, name: str, shard: str, does: str) -> dict:
    nb = json.loads(json.dumps(master))          # deep copy
    patched_knobs = 0
    for cell in nb["cells"]:
        src = "".join(cell["source"])
        if cell["cell_type"] == "markdown" and "# SBTS Canonical Experiment" in src:
            cell["source"] = [l + "\n" for l in
                              BANNER.format(shard=shard, does=does).split("\n")] + cell["source"]
        elif cell["cell_type"] == "code" and re.search(r"^RUN_MODE = ", src, re.M):
            src, n1 = re.subn(r'^RUN_MODE = "SMOKE".*$',
                              'RUN_MODE = "FULL"', src, count=1, flags=re.M)
            src, n2 = re.subn(r"^SHARD_GENERATORS = None.*$",
                              f"SHARD_GENERATORS = {shard}", src, count=1, flags=re.M)
            patched_knobs = n1 + n2
            cell["source"] = [l + "\n" for l in src.split("\n")[:-1]] + [src.split("\n")[-1]]
            cell["outputs"] = []
            cell["execution_count"] = None
    if patched_knobs != 2:
        raise SystemExit(f"{name}: expected to patch 2 knobs, patched {patched_knobs}. "
                         f"Has Cell 0 changed?")
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
    return nb


def main() -> int:
    if not MASTER.exists():
        raise SystemExit(f"missing {MASTER}")
    master = json.loads(MASTER.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, (shard, does) in VARIANTS.items():
        nb = build(master, name, shard, does)
        dst = OUT_DIR / f"{name}.ipynb"
        dst.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
        print(f"wrote {dst.relative_to(ROOT)}  (SHARD_GENERATORS = {shard})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
